name: Test
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  # detect whether any code changes are included in this PR
  changes:
    runs-on: ubuntu-slim
    permissions:
      # necessary to detect changes
      # https://github.com/dorny/paths-filter#supported-workflows
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        # dorny/paths-filter needs git clone for non-PR events
        # https://github.com/dorny/paths-filter#supported-workflows
        if: github.event_name != 'pull_request'
      - name: Filter Changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            code:
              - '.github/workflows/test.yml'
              - 'conda_pypi/**'
              - 'tests/**'
              - 'pyproject.toml'
              - 'pixi.lock'

  tests:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    name: ${{ matrix.os }}, ${{ matrix.pixi-env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        pixi-env: ["py310", "py311", "py312", "py313", "py314", "canary"]
        include:
          - os: macos-latest
            pixi-env: "py314"
    env:
      PIXI_ENV_NAME: test-${{ matrix.pixi-env }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: ${{ env.PIXI_ENV_NAME }}
      - name: Fix Ubuntu configuration
        if: startswith(matrix.os, 'ubuntu-')
        run:
          # Remove global pip config that interferes with isolated testing
          # See: https://github.com/actions/runner-images/blob/6d025759810a/images/ubuntu/scripts/build/install-python.sh#L15-L21
          sudo rm /etc/pip.conf
      - name: Setup project
        env:
          CHANNELS: ${{ env.PIXI_ENV_NAME == 'test-canary' && 'conda-forge, conda-canary/label/dev' || 'conda-forge' }}
        run: |
          pixi reinstall --environment ${{ env.PIXI_ENV_NAME }} conda-pypi
          pixi run --environment ${{ env.PIXI_ENV_NAME }} dev
          echo "channels: [${{ env.CHANNELS }}]" > .pixi/envs/${{ env.PIXI_ENV_NAME }}/.condarc
          pixi run --environment ${{ env.PIXI_ENV_NAME }} conda info
      - name: Run tests
        run: pixi run --environment ${{ env.PIXI_ENV_NAME }} test --basetemp=${{ runner.os == 'Windows' && 'D:\\temp' || runner.temp }} -vv

  linux-benchmarks:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    name: benchmarks py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["312"]
    env:
      PIXI_ENV_NAME: test-py${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: ${{ env.PIXI_ENV_NAME }}
      - name: Fix Ubuntu configuration
        run:
          # Remove global pip config that interferes with isolated testing
          # See: https://github.com/actions/runner-images/blob/6d025759810a/images/ubuntu/scripts/build/install-python.sh#L15-L21
          sudo rm /etc/pip.conf
      - name: Setup project
        run: |
          pixi reinstall --environment ${{ env.PIXI_ENV_NAME }} conda-pypi
          pixi run --environment ${{ env.PIXI_ENV_NAME }} dev
          echo "channels: [conda-forge]" > .pixi/envs/${{ env.PIXI_ENV_NAME }}/.condarc
          pixi run --environment ${{ env.PIXI_ENV_NAME }} conda info
      - name: Run benchmarks
        uses: CodSpeedHQ/action@d872884a306dd4853acf0f584f4b706cf0cc72a2 # v4.13.0
        with:
          mode: instrumentation
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run --environment ${{ env.PIXI_ENV_NAME }} benchmark

  # required check
  analyze:
    needs: [tests, linux-benchmarks]
    if: '!cancelled()'

    runs-on: ubuntu-slim
    steps:
      - name: Determine Success
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        id: alls-green
        with:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
